name: fablifestyle
favicon: null
layout_spectrum: 0.57606
typography_spectrum: 0.8166310517117381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27231191378086805
  lightness: 0.11817458085715771
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
