name: fablifestyle
favicon: null
layout_spectrum: 0.56804
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4dad9'
    - '#89776b'
    - '#b8bbb2'
    - '#5a4c41'
    - '#0e080a'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
